---
sidebar: sidebar 
permalink: ontap-security-hardening/autonomous-ransomware-protection.html 
keywords: tr-4569, ontap hardening guide, security, ARP, fpolicy, UBA, ransomware, machine learning, volume workloads, entropy 
summary: 'La fonctionnalité intégrée de machine learning d"ONTAP détecte les ransomwares en fonction des workloads de volume et de l"entropie.' 
---
= La protection anti-ransomware autonome de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour compléter l'analytique du comportement des utilisateurs pour Storage Workload Security, la protection anti-ransomware autonome de ONTAP analyse les workloads de volume et l'entropie pour détecter les ransomware, effectue une copie Snapshot et notifie l'administrateur lorsqu'une attaque est suspectée.

Outre la détection et la prévention des ransomwares à l'aide de l'analyse comportementale des utilisateurs FPolicy externes (UBA) avec NetApp Data Infrastructure Insights Storage Workload Security et l'écosystème de partenaires NetApp FPolicy, ONTAP 9.10.1 introduit une protection autonome contre les ransomwares.  La protection autonome contre les ransomwares ONTAP utilise une capacité d'apprentissage automatique (ML) intégrée qui examine l'activité de la charge de travail du volume ainsi que l'entropie des données pour détecter automatiquement les ransomwares.  Il surveille les activités différentes de celles de l'UBA afin de pouvoir détecter les attaques que l'UBA ne détecte pas.

Pour plus d'informations sur cette fonctionnalité, voir link:../ransomware-solutions/ransomware-overview.html["Solutions NetApp pour ransomware"] ou link:https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html["Documentation sur la protection anti-ransomware autonome de ONTAP"^].
