---
sidebar: sidebar 
permalink: ontap-security-hardening/security-hardening-overview.html 
keywords: tr-4569, ontap hardening guide, security, threats, threat landscape, hardening guide, introduction 
summary: 'Suivez ces conseils pour ONTAP afin d"aider votre entreprise à atteindre les objectifs de sécurité prescrits pour la confidentialité, l"intégrité et la disponibilité des systèmes d"information.' 
---
= Présentation du renforcement de la sécurité ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP propose un ensemble de commandes qui vous permettent d'utiliser en toute sécurité le système d'exploitation du stockage ONTAP, le logiciel de gestion des données n° 1 du secteur. Utilisez les conseils et les paramètres de configuration de ONTAP pour aider votre entreprise à atteindre les objectifs de sécurité prescrits en matière de confidentialité, d'intégrité et de disponibilité des systèmes d'information.

L'évolution du paysage actuel des menaces présente à une entreprise des défis uniques pour protéger ses ressources les plus précieuses : les données et les informations. Les menaces et vulnérabilités dynamiques et avancées auxquelles nous sommes confrontés sont de plus en plus sophistiquées. Associés à une augmentation de l'efficacité des techniques d'obfuscation et de reconnaissance de la part des intrus potentiels, les gestionnaires de systèmes doivent aborder de façon proactive la sécurité des données et de l'information.


NOTE: À partir de juillet 2024, le contenu du rapport technique _TR-4569: Security durcissante guide for ONTAP_, qui a été publié au préalable en format PDF, est disponible sur docs.netapp.com.
