---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices, SM-BC, SnapMirror Business Continuity 
permalink: business-continuity.html 
summary: 'Ces rapports techniques présentent la continuité de l"activité dans NetApp ONTAP, ainsi que les pratiques recommandées' 
---
= Rapports techniques sur la continuité de l'activité
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp propose une large gamme de solutions permettant de choisir l'emplacement optimal pour vos applications et vos données de manière à améliorer les performances à moindre coût. Protection des données, réplication et disponibilité continue : la gestion des données ONTAP simplifie la protection des données à l'aide d'une gestion des règles en une seule étape, tout en assurant la continuité de l'activité avec la synchronisation active MetroCluster et SnapMirror.

[NOTE]
====
Ces rapports techniques étendent la documentation sur link:https://docs.netapp.com/us-en/ontap/smbc/index.html["Synchronisation active de ONTAP SnapMirror"] les produits et link:https://docs.netapp.com/us-en/ontap-metrocluster/index.html["ONTAP MetroCluster"] .

====


== SnapMirror actif sync (anciennement SM-BC)

link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["Tr-4878 : synchronisation active SnapMirror"^] SnapMirror Active Sync est une solution de stockage disponible en continu avec une granularité au niveau des applications. Elle est disponible pour ONTAP sur les systèmes de stockage AFF ou ASA, afin de répondre aux besoins RPO 0 et RTO 0 des applications d'entreprise les plus stratégiques.



== MetroCluster

link:https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["Tr-4705 : architecture et conception de la solution NetApp MetroCluster"^]
Ce document présente l'architecture générale et les concepts de conception des fonctionnalités MetroCluster dans ONTAP.

*MetroCluster IP* link:https://www.netapp.com/pdf.html?item=/media/13481-tr4689pdf.pdf["Tr-4689 : IP NetApp MetroCluster"^] MetroCluster est une solution de stockage disponible en continu pour ONTAP sur les systèmes FAS et AFF. MetroCluster IP est la dernière évolution qui utilise un fabric de stockage back-end basé sur Ethernet. MetroCluster IP fournit une configuration hautement redondante afin de répondre aux besoins des applications d'entreprise les plus stratégiques. MetroCluster IP est inclus dans ONTAP et fournit une connectivité NAS et SAN pour les clients et les serveurs qui utilisent le stockage ONTAP.

*FC MetroCluster*
link:https://www.netapp.com/pdf.html?item=/media/13482-tr4375.pdf["Tr-4375 : FC NetApp MetroCluster"^]
MetroCluster assure une disponibilité continue des données dans les data centers répartis géographiquement pour les applications stratégiques. Découvrez les pratiques recommandées, les décisions de conception et les configurations prises en charge par MetroCluster FC.
