---
settings:
  name: ONTAP Technical Reports
  search: ontap-technical-reports, ontap-apps-dbs, netapp-solutions-sap
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Rapports techniques de ONTAP
    url: "/index.html"
  - title: Applications et bases de données
    url: "/apps-dbs.html"
  - title: Continuité de l'activité
    url: "/business-continuity.html"
  - title: Protection des données et reprise d'activité
    url: "/data-protection-disaster-recovery.html"
  - title: Volumes FlexCache et FlexGroup
    url: "/nas-containers.html"
  - title: NAS
    url: "/nas.html"
  - title: Mise en réseau
    url: "/networking.html"
  - title: SAN
    url: "/san.html"
  - title: Sécurité
    url: "/security.html"
  - title: Guides de renforcement de la sécurité
    url: "/security-hardening-guides.html"
  - title: SnapCenter
    url: "/snapcenter.html"
  - title: Tiering
    url: "/tiering.html"
  - title: Virtualisation
    url: "/virtualization.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
