---
permalink: san.html 
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, SAN, NVMe, NVMeoF, NVMeoTCP, NVMeoFC, iSCSI, fibre channel, fiber channel, igroups, namespaces, namespace, LUN, subsystem, best practices, best-practices 
summary: Ces rapports techniques présentent les protocoles de niveau bloc dans ONTAP, ainsi que les pratiques recommandées. 
---
= Rapports techniques sur les SAN ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le stockage SAN de ONTAP offre une expérience SAN simplifiée qui assure la haute disponibilité des bases de données stratégiques de votre entreprise et d'autres workloads SAN. Grâce à l'intégration de services de données exceptionnels avec les bases de données Oracle, SAP et Microsoft SQL Server, ainsi que l'utilisation de VMware et d'autres hyperviseurs de premier plan, les systèmes SAN ONTAP accélèrent le retour sur investissement des applications de bases de données d'entreprise.

[NOTE]
====
Ces rapports techniques sont détaillés dans link:https://docs.netapp.com/us-en/ontap/san-management/index.html["Gestion du stockage SAN ONTAP"^]la documentation produit.

====
link:https://www.netapp.com/pdf.html?item=/media/10680-tr4080.pdf["Tr-4080 : bonnes pratiques pour le SAN moderne dans ONTAP"^]
Découvrez les protocoles de niveau bloc dans ONTAP ainsi que des recommandations.

link:https://www.netapp.com/pdf.html?item=/media/10681-tr4684.pdf["Tr-4684 : implémentation et configuration de SAN modernes avec NVMe over Fabrics (NVMe-of)"^]
Découvrez comment implémenter et configurer le transport NVMe over Fabrics (NVMe over Fibre Channel et NVMe over TCP). Il aborde des thèmes tels que la conception, l'implémentation, la configuration, les instructions de gestion, ainsi que les pratiques recommandées pour créer des solutions SAN modernes haute disponibilité et haute performance basées sur les protocoles et les transports NVMe.

link:https://www.netapp.com/pdf.html?item=/media/85671-tr-4968.pdf["Tr-4968 : disponibilité et intégrité des données des baies 100 % SAN NetApp"^]
Découvrez comment les différentes fonctionnalités de protection et d'intégrité des données des systèmes SAN fonctionnent pour optimiser la continuité des applications, ainsi que les pratiques recommandées pour la conception, l'implémentation et la gestion d'un réseau SAN.

link:https://www.netapp.com/pdf.html?item=/media/9222-nva-1145-design.pdf["Solution Flash connectée au cloud SAN moderne"^]
Cette architecture vérifiée NetApp a été conçue et vérifiée conjointement par NetApp, VMware et Broadcom. Elle utilise les dernières solutions technologiques Brocade, Emulex et VMware vSphere ainsi que le stockage 100 % Flash NetApp, qui définit un nouveau standard en matière de stockage SAN d'entreprise et de protection des données pour une plus grande valeur commerciale.
