---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, MFA, best practices, best-practices, TR-4569 
permalink: security-hardening-guides.html 
summary: 'Ces rapports techniques fournissent des conseils sur la manière de renforcer NetApp ONTAP ainsi que d"autres produits associés à ONTAP.' 
---
= Guides de renforcement de la sécurité
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ces rapports techniques vous indiquent comment renforcer NetApp ONTAP et les autres produits NetApp.

[NOTE]
====
Ces rapports techniques se développent sur le link:https://docs.netapp.com/us-en/ontap/security-encryption/index.html["Sécurité et chiffrement des données ONTAP"] documentation produit.

====


== Guides de durcissement

link:https://docs.netapp.com/us-en/ontap/ontap-security-hardening/security-hardening-overview.html["Tr-4569 : guide sur le renforcement de la sécurité pour NetApp ONTAP"^] Découvrez comment configurer NetApp ONTAP pour aider les entreprises à atteindre les objectifs de sécurité prescrits en matière de confidentialité, d'intégrité et de disponibilité des systèmes d'information.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-otv-hardening-overview.html["Guide de renforcement de la sécurité des outils ONTAP pour VMware vSphere"] Découvrez comment configurer les outils ONTAP pour VMware vSphere pour aider les entreprises à atteindre les objectifs de sécurité prescrits en matière de confidentialité, d'intégrité et de disponibilité des systèmes d'information.

link:https://www.netapp.com/pdf.html?item=/media/82393-tr-4957.pdf["Tr-4957 : guide sur le renforcement de la sécurité pour NetApp SnapCenter"^]
Découvrez comment configurer le logiciel NetApp SnapCenter pour aider les entreprises à atteindre les objectifs de sécurité prescrits en matière de confidentialité, d'intégrité et de disponibilité des systèmes d'information.

link:https://www.netapp.com/pdf.html?item=/media/83591-tr-4963.pdf["Tr-4963 : guide sur le renforcement de la sécurité : BlueXP Cloud Backup pour les applications"^]
Découvrez comment configurer la sauvegarde dans le cloud NetApp pour les applications afin d'aider les entreprises à atteindre les objectifs de sécurité prescrits pour la confidentialité, l'intégrité et la disponibilité des systèmes d'information.

link:https://netapp.com/pdf.html?item=/media/78654-tr-4943.pdf["Tr-4943 : guide sur le renforcement de la sécurité pour NetApp Active IQ Unified Manager"^]
Découvrez comment configurer NetApp Active IQ Unified Manager pour aider les entreprises à atteindre les objectifs de sécurité prescrits en matière de confidentialité, d'intégrité et de disponibilité des systèmes d'information.

link:https://www.netapp.com/pdf.html?item=/media/78941-tr-4945.pdf["Tr-4945 : guide de renforcement de la sécurité pour le SDK de gestion NetApp"^]
Découvrez comment configurer le SDK de gestion NetApp (NMSDK) pour aider les entreprises à atteindre les objectifs de sécurité prescrits en matière de confidentialité, d'intégrité et de disponibilité des systèmes d'information.
