---
permalink: storage-efficiency.html 
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
summary: 'Ces rapports techniques présentent l"efficacité du stockage dans NetApp ONTAP, ainsi que les pratiques recommandées.' 
---
= Rapports techniques sur l'efficacité du stockage ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP propose un portefeuille complet de fonctionnalités d'efficacité du stockage. Combinez la compression, la déduplication et la compaction des données à la volée pour réduire les coûts du stockage et optimiser la capacité de stockage. Par ailleurs, vous pouvez multiplier vos économies grâce aux copies NetApp Snapshot compactes et aux technologies d'allocation dynamique, de réplication et de clonage.

[NOTE]
====
La documentation procédurale pour la déduplication est disponible à la link:https://docs.netapp.com/us-en/ontap/volumes/enable-deduplication-volume-task.html["documentation sur la déduplication"^]section Documentation procédurale pour la compression, à la section link:https://docs.netapp.com/us-en/ontap/volumes/enable-data-compression-volume-task.html["documentation sur la compression"^]Documentation procédurale pour l'efficacité de stockage sensible à la température, à la section link:https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["documentation relative à l'efficacité du stockage sensible à la température"^]Documentation procédurale pour la compaction, se trouve à l'adresse link:https://docs.netapp.com/us-en/ontap/volumes/enable-inline-data-compaction-fas-systems-task.html["documentation de compactage"^]

====