---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: 'L"automatisation permet aux entreprises de faire évoluer les déploiements « zéro confiance » en plus de procédures manuelles, pour se défendre contre les activités impropres qui sont également automatisées' 
---
= Contrôles d'orchestration et d'automatisation de la sécurité NetApp externes à ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'automatisation vous permet d'effectuer un processus ou une procédure avec une assistance humaine minimale. L'automatisation permet aux entreprises d'étendre les déploiements « zéro confiance » bien au-delà des procédures manuelles pour se défendre contre les activités imcretes également automatisées.

Ansible est un outil open source de provisionnement logiciel, de gestion de la configuration et de déploiement des applications. Il fonctionne sur de nombreux systèmes Unix et peut configurer à la fois les systèmes Unix et Microsoft Windows. Il comprend son propre langage déclaratif pour décrire la configuration du système. Ansible a été écrit par Michael DeHaan et acquis par Red Hat en 2015. Ansible se connecte temporairement à distance sans agent via SSH ou Windows Remote Management (permettant l'exécution à distance de PowerShell). NetApp a développé plus de https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx["150 modules Ansible pour le logiciel ONTAP"^], permettant une intégration supplémentaire avec la structure d'automatisation Ansible. Les modules Ansible pour NetApp fournissent un ensemble d'instructions sur la manière de définir l'état souhaité et de le relayer vers l'environnement NetApp cible. Les modules sont conçus pour prendre en charge des tâches telles que la configuration de licences, la création d'agrégats et de machines virtuelles de stockage, la création de volumes et la restauration de snapshots, pour n'en nommer que quelques-uns. Un rôle Ansible a été https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["Publié sur GitHub"^] spécifique au guide de déploiement des fonctionnalités unifiées du Ministère de la Défense NetApp.

En utilisant la bibliothèque de modules disponibles, les utilisateurs peuvent facilement développer des playbooks Ansible et les personnaliser en fonction de leurs propres applications et des besoins de l'entreprise pour automatiser des tâches courantes. Une fois qu'un PlayBook est écrit, vous pouvez l'exécuter pour exécuter la tâche spécifiée, ce qui permet de gagner du temps et d'améliorer la productivité. NetApp a créé et partagé des exemples de playbooks pouvant être utilisés directement ou personnalisés en fonction de vos besoins.

Data Infrastructure Insights est un outil de surveillance de l'infrastructure qui vous donne une visibilité sur l'ensemble de votre infrastructure.  Avec Data Infrastructure Insights, vous pouvez surveiller, dépanner et optimiser toutes vos ressources, y compris vos instances de cloud public et vos centres de données privés.  Data Infrastructure Insights peut réduire le temps moyen de résolution de 90 % et empêcher 80 % des problèmes de cloud d'affecter les utilisateurs finaux.  Il peut également réduire les coûts d’infrastructure cloud de 33 % en moyenne et réduire votre exposition aux menaces internes en protégeant vos données grâce à des renseignements exploitables.  La fonctionnalité de sécurité de la charge de travail de stockage de Data Infrastructure Insights permet l'analyse du comportement des utilisateurs avec l'IA et le ML pour alerter lorsque des comportements d'utilisateur aberrants se produisent en raison d'une menace interne.  Pour ONTAP, Storage Workload Security utilise le moteur Zero Trust FPolicy.
