---
permalink: zero-trust/zero-trust-cloud-deployments.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, netapp, cloud, deployments, hybrid, amazon web services, aws, microsoft azure, google cloud platform, gcp, GCNV, Google Cloud, Google Cloud NetApp Volumes 
summary: Les options NetApp étendent les systèmes de gestion des données sur site au cloud hybride avec les principaux fournisseurs de cloud, avec prise en charge des contrôles de sécurité « zéro confiance » 
---
= Zero Trust et déploiements de cloud hybride
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp est l'autorité en matière de données pour le cloud hybride. NetApp propose une variété d'options pour étendre les systèmes de gestion de données sur site au cloud hybride avec Amazon Web Services (AWS), Microsoft Azure, Google Cloud et d'autres fournisseurs de cloud de premier plan. Les solutions cloud hybrides NetApp prennent en charge les mêmes contrôles de sécurité Zero Trust que ceux disponibles avec les systèmes ONTAP sur site et le stockage défini par logiciel ONTAP Select .

Vous pouvez facilement étendre la capacité des clouds publics sans contraintes CAPEX typiques en utilisant des services de fichiers cloud natifs de classe entreprise pour AWS (FSxN), Google Cloud (GCNV) et Azure NetApp Files pour Microsoft Azure. Idéals pour les charges de travail gourmandes en données telles que l'analyse et DevOps, ces services de données cloud combinent le stockage élastique à la demande en tant que service de NetApp avec la gestion des données ONTAP dans une offre entièrement gérée.

ONTAP permet le déplacement de données entre vos systèmes ONTAP sur site et l'environnement de stockage AWS, Google Cloud ou Azure avec le logiciel de réplication de données NetApp SnapMirror .
