---
sidebar: sidebar 
permalink: afx/afx-architecture.html 
keywords: netapp afx, architecture, storage availability zone, nvram, raid, disaggregated 
summary: NetApp AFX introduit des différences architecturales importantes par rapport à unified ONTAP dans la manière dont le stockage est présenté, dont les nœuds interagissent avec les disques et dont la capacité est gérée. 
---
= En quoi l’architecture NetApp AFX diffère-t-elle de ONTAP unifié
:allow-uri-read: 
:icons: font
:imagesdir: ../media/afx/


[role="lead"]
NetApp AFX introduit des différences architecturales importantes par rapport à unified ONTAP dans la manière dont le stockage est présenté, dont les nœuds interagissent avec les disques et dont la capacité est gérée.

Nous avons précédemment présenté un aperçu général de la façon dont l'architecture Unified ONTAP fournit le stockage de fichiers, d’objets et de blocs via des paires HA directement connectées, chacune possédant son propre ensemble de disques et présentant une capacité physique via des agrégats de disques. Dans cette section, nous examinerons plus en détail certaines des principales différences entre les architectures Unified ONTAP et NetApp AFX.



[[how-to-tell-if-a-system-is-running-netapp-afx]]
== Comment savoir si un système exécute NetApp AFX

La principale façon de vérifier si votre système exécute NetApp AFX est d'exécuter la commande suivante :

[listing]
----
AFX::> node show -fields personality
node             personality
---------------- -----------
afx-01           AFX
afx-02           AFX
----
Un autre indice est la nouvelle zone de disponibilité du stockage, mais ce concept est également disponible pour les NetApp All-SAN Arrays (ASA). Vous pouvez consulter votre capacité via cette commande.

[listing]
----
AFX::> storage availability-zone show
                     Availability Zone Name: storage_availability_zone_0
                     Availability Zone UUID: 545cb59f-32e9-11f1-a2f5-d039eabdd925
                                 Total Size: 69.59TB
                              Physical Used: 837.1GB
                      Physical Used Percent: 1%
                                  Available: 68.77TB
                              Metadata Used: 837.1GB
                  Log and Recovery Metadata: 834.6GB
                              Delayed Frees: 2.50GB
 Physical User Data Without Snapshot Copies: 17.24MB
  Logical User Data Without Snapshot Copies: 17.24MB
   Efficiency Ratio Without Snapshot Copies: 1.00:1
               Space Full Threshold Percent: 98%
        Space Nearly Full Threshold Percent: 95%
----


[[architecture-topics]]
== Sujets d'architecture

* link:afx-architecture-node-disk.html["Relations nœud-disque"]
* link:afx-architecture-capacity-pool.html["Pool de capacité unique"]
* link:afx-architecture-nvram-ha.html["Comportement de basculement HA et NVRAM répliquée"]
* link:afx-architecture-independent-scale.html["Échelle linéaire indépendante"]
* link:afx-architecture-raid.html["Modifications RAID"]
* link:afx-architecture-storage-efficiency.html["efficacité de stockage"]
* link:afx-architecture-feature-support.html["Modifications apportées à la prise en charge des fonctionnalités ONTAP"]
* link:afx-architecture-flexgroup.html["Améliorations de la gestion FlexGroup"]
* link:afx-architecture-volume-moves.html["Mouvements de volume"]
* link:afx-architecture-cluster-scale.html["Échelle du cluster"]
* link:afx-architecture-root-volume.html["modifications du volume racine"]


[cols="1,1"]
|===


| link:afx-whats-new.html["Précédent"] | link:afx-architecture-node-disk.html["Ensuite : Relations nœud-disque"] 
|===